In [3]:
#Exercise 6.2
#Problem 1, Part a

#Partial Pivoting:

import numpy as np
import math
import matplotlib.pyplot as plt

N=4
#A=np.zeros((N,N))

#for i in range(N):
#    for j in range(N):
#        A[i,j]=np.random.randint(-10,10)

A = np.array([[2, 1, 4, 1],
              [3, 4,-1,-1],
              [1,-4, 1, 5],
              [2,-2, 1, 3]], float)

print(A)

v=np.array([-4,3,9,7],float)
#v=np.zeros(N)

#for i in range(N):
#    v[i]=np.random.randint(-10,10)

x_safety=np.linalg.solve(A,v)

for m in range(N):
    for k in range(N-1):
        #Choose largest pivot element below (and including) k
        maxindex = abs(A[k:,k]).argmax() + k
        #Swap rows
        if (maxindex != k):
            A[[k,maxindex]] = A[[maxindex, k]]
            v[[k,maxindex]] = v[[maxindex, k]]
        for row in range(k+1, N):
            multiplier = A[row][k]/A[k][k]
            #the only one in this column since the rest are zero
            A[row][k]=0
            for col in range(k + 1, N):
                A[row][col] = A[row][col] - multiplier*A[k][col]
            #Equation solution column
            v[row] = v[row] - multiplier*v[k]
    
    div=A[m,m]
    A[m,:]/=div
    v[m]/=div
    
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:]-=mult*A[m,:]
        v[i]-=mult*v[m]
        
x=np.empty(N,float)

for m in range(N-1,-1,-1):
    x[m]=v[m]
    for i in range(m+1,N):
        x[m]-=A[m,i]*x[i]

print("Gauss-Jordan elim: ",np.around(x,2))
print("Just to make sure: ",np.around(x_safety,2))

[[ 2.  1.  4.  1.]
 [ 3.  4. -1. -1.]
 [ 1. -4.  1.  5.]
 [ 2. -2.  1.  3.]]
Gauss-Jordan elim:  [ 2. -1. -2.  1.]
Just to make sure:  [ 2. -1. -2.  1.]


In [5]:
#Problem 1, part b

import numpy as np
import math
import matplotlib.pyplot as plt

N=4

A = np.array([[0, 1, 4, 1],
              [3, 4,-1,-1],
              [1,-4, 1, 5],
              [2,-2, 1, 3]], float)

v=np.array([-4,3,9,7],float)

x_safety1=np.linalg.solve(A,v)

for m in range(N):
    
    for k in range(N-1):
        maxindex = abs(A[k:,k]).argmax() + k
        if (maxindex != k):
            A[[k,maxindex]] = A[[maxindex, k]]
            v[[k,maxindex]] = v[[maxindex, k]]
        for row in range(k+1, N):
            multiplier = A[row,k]/A[k,k]
            A[row,k] = 0
            for col in range(k + 1, N):
                A[row,col] = A[row,col] - multiplier*A[k,col]
            v[row] = v[row] - multiplier*v[k]
    
    div=A[m,m]
    A[m,:]/=div
    v[m]/=div
    
    for i in range(m+1,N):
        mult = A[i,m]
        A[i,:]-=mult*A[m,:]
        v[i]-=mult*v[m]
        
x=np.empty(N,float)

for m in range(N-1,-1,-1):
    x[m]=v[m]
    for i in range(m+1,N):
        x[m]-=A[m,i]*x[i]
        
print("Gauss-Jordan elim with pivot : ",np.around(x,2))
print("Just to make sure (np.linalg): ",np.around(x_safety1,2))

Gauss-Jordan elim with pivot :  [ 1.62 -0.43 -1.24  1.38]
Just to make sure (np.linalg):  [ 1.62 -0.43 -1.24  1.38]
